language: python

python:
  - "2.7"

sudo: required

services:
  - docker

cache:
  directories:
    - $HOME/.cache/pip

install:
    - pip install docker-compose
    - pip install -r pip-deploy.txt

before_script:
  - fab stage prebuild
  - docker-compose up -d rapidprodb
  - docker-compose up -d rapidproredis
  - docker-compose build rapidpro

script:
  - docker-compose run rapidpro setuplocaldb

after_success:
  ./travis_success.sh
