language: python

python:
  - "2.7"

sudo: required

services:
  - docker

cache:
  directories:
    - $HOME/.cache/pip

install:
    - pip install docker-compose

before_script:
  - docker-compose up -d rapidprodb
  - docker-compose up -d rapidproredis
  - docker-compose build rapidpro

script:
  - docker-compose run rapidpro setupdb
