language: python

python:
  - "2.7"

sudo: required

services:
  - docker

env:
  DOCKER_IMAGE_REPO: 387526361725.dkr.ecr.eu-west-1.amazonaws.com
  AWS_REGION: eu-west-1

cache:
  directories:
    - $HOME/.cache/pip

install:
  - pip install -r pip-deploy.txt
  - sudo apt-get -qq install -y zip

before_script:
  - docker-compose up -d rapidprodb
  - docker-compose up -d rapidproredis
  - docker-compose build rapidpro

script:
- docker-compose run rapidpro setuplocaldb

after_success:
  ./travis_deploy.sh
