rapidprodb:
  image: "mdillon/postgis"

rapidproredis:
    image: "redis"

rapidpro:
  build: .
  volumes:
      - ./:/code
  environment:
      DBHOST: "rapidprodb"
      DBUSER: "postgres"
      DBPASS: ""
      REDISHOST: "rapidproredis"
      STATIC_DIR: "/var/www/static/"
  command: start 
  ports:
    - "5000:5000"
    - "8000:8000"
  links:
    - rapidprodb
    - rapidproredis
