version: "2"

volumes:
  static_content:
    driver: local

services:
  rapidprodb:
    image: "mdillon/postgis"

  rapidproredis:
    image: "redis"

  rapidpro:
    build: .
    environment:
        RDS_HOSTNAME: "rapidprodb"
        RDS_USERNAME: "postgres"
        RDS_PASSWORD: ""
        RDS_PORT: ""
        RDS_DB_NAME: "postgres"
        REDISHOST: "rapidproredis"
        STATIC_DIR: "/var/www/static/"
    command: start
    ports:
      - "5000:5000"
      - "8000:8000"
    links:
      - rapidprodb
      - rapidproredis
    volumes:
      - static_content:/var/www/static/:rw
    extra_hosts:
      - "set.local:192.168.10.10"

  nginx:
    image: nginx:alpine
    volumes:
      - static_content:/var/www/static/:rw
      - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf:rw
    links:
      - rapidpro
    ports:
      - "80:80"
    extra_hosts:
      - "set.local:192.168.10.10"
