branch-defaults:
  default:
    environment: rapidpro-dev
  develop:
    environment: rapidpro-dev
  master:
    environment: rapidpro-dev
global:
  application_name: rapidpro
  default_ec2_keyname: aws-deploy
  default_platform: 64bit Amazon Linux 2016.03 v2.1.0 running Multi-container Docker
    1.9.1 (Generic)
  default_region: eu-west-1
  profile: null
  sc: git
deploy:
    artifact: tmp/deploy.zip
